name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  ID_NUMBER: ${{ github.run_number }}
  SURGE_DOMAIN: ci-test-website.surge.sh

jobs:
  build-and-deploy-gh-pages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --silent
      - name: Build website
        env:
          URL_PRODUCTION: https://fabiofranca02.github.io
          BASE_URL: /ci-test/
        run:
          npm run build --if-present
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  build-and-deploy-surge:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --silent
      - name: Build website
        env:
          URL_PRODUCTION: https://${{ env.SURGE_DOMAIN }}
          BASE_URL: /
        run: |
          npm run build --if-present
          npm install -g surge

      - name: Deploy to surge -> ${{ env.SURGE_DOMAIN }}
        run: surge ./build ${{ env.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
